const SET_USER = "SET_USER";
const CLEAR_USER = "CLEAR_USER";

const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const CLEAR_CART = "CLEAR_CART";
const INCREASE = "INCREASE";
const DECREASE = "DECREASE";

export {
  SET_USER,
  CLEAR_USER,
  ADD_TO_CART,
  REMOVE_FROM_CART,
  CLEAR_CART,
  INCREASE,
  DECREASE,
};
